// Radar de Pautas (beta) — curadoria algorítmica, sem IA.
const STORE_KEY='argos_radar_beta_v1';
const PROXY_URL='/api/radar/fetch';
export const RADAR_TTL_DAYS_DEFAULT=10;
export const RADAR_MAX_KEYWORDS=5;
export const RADAR_MAX_ITEMS_PER_QUERY=10;
export const RADAR_LANGUAGES=[{id:'pt-BR',label:'Português (Brasil)',news:'hl=pt-BR&gl=BR&ceid=BR:pt-419'},{id:'en-US',label:'Inglês (EUA)',news:'hl=en-US&gl=US&ceid=US:en'},{id:'es-419',label:'Espanhol (Am. Latina)',news:'hl=es-419&gl=MX&ceid=MX:es-419'}];
export const RADAR_SOURCES=[{id:'news',label:'Notícias',hint:'Google Notícias',kind:'noticia'},{id:'video',label:'Vídeos',hint:'YouTube',kind:'video'},{id:'social',label:'Redes sociais',hint:'Mastodon',kind:'social'},{id:'reddit',label:'Opiniões',hint:'Reddit',kind:'discussao'}];
export const RADAR_DEFAULT_SETTINGS={language:'pt-BR',sources:{news:true,video:true,social:false,reddit:false}};
export function emptyBriefing(companyId=''){return{companyId,active:true,business:'',keywords:[],audience:'',themes:[],exclude:[],competitors:[],feeds:[],notes:'',updatedAt:null}}
export function emptyStore(){return{version:3,ttlDays:RADAR_TTL_DAYS_DEFAULT,settings:{...RADAR_DEFAULT_SETTINGS,sources:{...RADAR_DEFAULT_SETTINGS.sources}},briefings:{},items:[],saved:[],lastScanAt:null}}
export function loadRadarStore(){try{const raw=JSON.parse(localStorage.getItem(STORE_KEY));if(!raw||typeof raw!=='object')return emptyStore();const store={...emptyStore(),...raw};store.briefings=Object.fromEntries(Object.entries(store.briefings||{}).map(([id,b])=>[id,normalizeBriefing(b)]));store.settings=normalizeSettings(store.settings,Object.values(store.briefings)[0]);return store}catch{return emptyStore()}}
export function normalizeSettings(settings,b){const base={...RADAR_DEFAULT_SETTINGS,sources:{...RADAR_DEFAULT_SETTINGS.sources}};if(!settings&&b){if(b.language)base.language=b.language;if(b.sources)base.sources={...base.sources,...b.sources};return base}return{...base,...(settings||{}),sources:{...base.sources,...(settings?.sources||{})}}}
export function saveRadarStore(store){try{localStorage.setItem(STORE_KEY,JSON.stringify(store))}catch(e){console.warn('radar: não consegui salvar',e)}return store}
export function parseList(text,{splitDots=true}={}){const parts=String(text||'').split(/[\n,;]+/).map(s=>s.trim()).filter(Boolean);if(!splitDots)return parts;const out=[];for(const part of parts){if(/^https?:\/\//i.test(part)||/\.(com|br|net|org|io|xml|rss)\b/i.test(part)){out.push(part);continue}out.push(...part.split(/(?<=\p{L})\.(?=\p{L})/gu).map(x=>x.trim()).filter(Boolean))}return out}
export function normalizeBriefing(b){if(!b)return b;return{...emptyBriefing(b.companyId),...b,themes:parseList(listToText(b.themes)),keywords:parseList(listToText(b.keywords)),competitors:parseList(listToText(b.competitors)),exclude:parseList(listToText(b.exclude)),feeds:parseList((b.feeds||[]).join('\n'),{splitDots:false})}}
export function listToText(list){return(Array.isArray(list)?list:[]).join(', ')}
function normalize(text){return String(text||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
export function hashtagOf(term){return normalize(term).replace(/[^a-z0-9]+/g,'')}
export function briefingTerms(b){return[...(b.keywords||[]),...(b.themes||[])].map(t=>String(t||'').trim()).filter(Boolean).slice(0,RADAR_MAX_KEYWORDS)}
export function briefingQueries(b,settings=RADAR_DEFAULT_SETTINGS){const cfg=normalizeSettings(settings,b),lang=RADAR_LANGUAGES.find(l=>l.id===cfg.language)||RADAR_LANGUAGES[0],terms=briefingTerms(b),out=[];if(cfg.sources.news)for(const term of terms)out.push({source:'Google Notícias',kind:'noticia',parser:'xml',term,url:`https://news.google.com/rss/search?q=${encodeURIComponent(`"${term}" when:7d`)}&${lang.news}`,retryUrl:`https://news.google.com/rss/search?q=${encodeURIComponent(`${term} when:7d`)}&${lang.news}`});if(cfg.sources.video)for(const term of terms)out.push({source:'YouTube',kind:'video',parser:'youtube',term,url:`https://www.youtube.com/results?search_query=${encodeURIComponent(`${term} novidades OR opinião OR atualização`)}&sp=EgQIAxAB`});if(cfg.sources.social)for(const term of terms){const tag=hashtagOf(term);if(tag.length>=3)out.push({source:'Mastodon',kind:'social',parser:'xml',term,emptyOn404:true,url:`https://mastodon.social/tags/${tag}.rss`})}if(cfg.sources.reddit)for(const term of terms.slice(0,3))out.push({source:'Reddit',kind:'discussao',parser:'xml',term,url:`https://www.reddit.com/search.rss?q=${encodeURIComponent(term)}&sort=top&t=week&limit=10`});for(const feed of b.feeds||[])if(/^https?:\/\//i.test(feed))out.push({source:'Feed do cliente',kind:'feed',parser:'xml',term:'',url:feed});return out}
export async function fetchFeed(url,{signal,emptyOn404=false}={}){const res=await fetch(`${PROXY_URL}?url=${encodeURIComponent(url)}`,{signal});if(!res.ok){if(res.status===404)throw new Error('A varredura em tempo real não está disponível neste ambiente.');throw new Error(`Falha ao buscar a fonte (${res.status})`)}const data=await res.json();if(!data?.ok){if(data?.status===404&&emptyOn404)return'';if(data?.status===429)throw new Error('a fonte limitou o acesso (429)');throw new Error(data?.error||'Fonte não respondeu')}return data.body}
function pick(node,...names){for(const name of names){const el=node.getElementsByTagName(name)[0];if(el?.textContent)return el.textContent.trim()}return''}
function stripTags(html){return String(html||'').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/\s+/g,' ').trim()}
export function parseFeedXml(xml,fallbackSource=''){const doc=new DOMParser().parseFromString(String(xml||''),'text/xml');if(doc.getElementsByTagName('parsererror').length)return[];const feedTitle=pick(doc.documentElement,'title')||fallbackSource,nodes=[...doc.getElementsByTagName('item'),...doc.getElementsByTagName('entry')],items=[];for(const node of nodes.slice(0,RADAR_MAX_ITEMS_PER_QUERY)){let link=pick(node,'link');if(!link){const el=[...node.getElementsByTagName('link')].find(x=>x.getAttribute('href'));link=el?.getAttribute('href')||''}if(!link)continue;const body=stripTags(pick(node,'description','summary','content')),title=stripTags(pick(node,'title'))||firstSentence(body);if(!title)continue;const published=pick(node,'pubDate','published','updated','dc:date'),d=published?new Date(published):null,sourceName=stripTags(pick(node,'source')||feedTitle)||fallbackSource;items.push({title:stripSourceSuffix(title,sourceName),url:link.trim(),snippet:body.slice(0,260),sourceName,publishedAt:d&&!Number.isNaN(d.getTime())?d.toISOString():null})}return items}
function firstSentence(text,max=120){const t=String(text||'').trim();if(!t)return'';const cut=t.slice(0,max),stop=cut.search(/[.!?](\s|$)/);return(stop>25?cut.slice(0,stop):cut).trim()+(t.length>max&&stop<=25?'…':'')}
export function parseYouTubeHtml(html){const match=String(html||'').match(/ytInitialData\s*=\s*(\{.+?\})\s*;\s*<\/script>/s);if(!match)return[];let data;try{data=JSON.parse(match[1])}catch{return[]}const found=[];const walk=(node,depth=0)=>{if(!node||typeof node!=='object'||depth>30||found.length>=RADAR_MAX_ITEMS_PER_QUERY)return;if(node.videoRenderer?.videoId)found.push(node.videoRenderer);if(Array.isArray(node)){for(const child of node)walk(child,depth+1);return}for(const key of Object.keys(node))walk(node[key],depth+1)};walk(data);return found.map(v=>{const title=v.title?.runs?.[0]?.text||v.title?.simpleText||'',channel=v.ownerText?.runs?.[0]?.text||v.longBylineText?.runs?.[0]?.text||'YouTube',desc=(v.detailedMetadataSnippets?.[0]?.snippetText?.runs||[]).map(r=>r.text).join('');return{title:stripTags(title),url:`https://www.youtube.com/watch?v=${v.videoId}`,snippet:stripTags(desc).slice(0,260),sourceName:stripTags(channel),publishedAt:relativeToIso(v.publishedTimeText?.simpleText||'')}}).filter(v=>v.title)}
export function relativeToIso(text,now=new Date()){const t=normalize(text),m=t.match(/(\d+)\s*(segundo|minuto|hora|dia|semana|m[eê]s|mes|ano|second|minute|hour|day|week|month|year)/);if(!m)return null;const n=Number(m[1]),u=m[2],h=/segundo|second/.test(u)?0:/minuto|minute/.test(u)?n/60:/hora|hour/.test(u)?n:/dia|day/.test(u)?n*24:/semana|week/.test(u)?n*168:/m[eê]s|mes|month/.test(u)?n*720:n*8760;return new Date(now.getTime()-h*3600000).toISOString()}
export function stripSourceSuffix(title,sourceName){const t=String(title||'').trim(),src=String(sourceName||'').trim();if(!src)return t;const tail=new RegExp(`\\s*[-–—|]\\s*${src.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}\\s*$`,'i');return t.replace(tail,'').trim()||t}
export function cleanSnippet(snippet,title){const text=String(snippet||'').trim();if(!text)return'';const a=normalize(text).replace(/\s+/g,' '),b=normalize(title).replace(/\s+/g,' ');if(b&&(a.startsWith(b)||a.includes(b))){const rest=text.replace(new RegExp(String(title).replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i'),'').replace(/^[\s\-–—|·]+/,'').trim();return rest.length>25?rest:''}return text}
export function urlKey(url){try{const u=new URL(url);u.hash='';[...u.searchParams.keys()].forEach(k=>{if(/^utm_|^fbclid$|^gclid$/i.test(k))u.searchParams.delete(k)});return u.toString().replace(/\/$/,'').toLowerCase()}catch{return String(url||'').toLowerCase()}}
const COMMERCIAL_RX=/(compre|comprar|preço|preco|orçamento|orcamento|promoção|promocao|desconto|cupom|oferta|frete|parcelamento|assine|assinatura|matr[ií]cula|inscreva-se|cadastre-se|agende|solicite|fale com|whatsapp|landing page|lp |checkout|loja online|e-commerce|vagas? abertas?|contrate|serviço|servico|plano mensal|grátis por \d|teste grátis|free trial)/i;
const EDITORIAL_RX=/(lança|lanca|lançou|anuncia|anunciou|novo|nova|novidade|atualiza|atualização|update|mudança|muda|estudo|pesquisa|dados|tendência|tendencia|viral|meme|opinião|opiniao|debate|polêmica|polemica|descoberta|recorde|cresce|queda|alerta|explica|como funciona|história|historia|curiosidade|dica|guia|caso|futuro|impacto|por que|porque|versus| vs |ranking|lista|melhores|erros|mitos)/i;
const SALES_URL_RX=/(\/checkout|\/cart|\/carrinho|\/produto\/|\/product\/|\/shop\/|\/loja\/|\/pricing|\/precos|\/preços|\/orcamento|\/orçamento|\/agendar|\/contato|\/contact|\/signup|\/register|\/subscribe)/i;
function commercialPenalty(item){const text=`${item.title} ${item.snippet}`;let p=0;if(COMMERCIAL_RX.test(text))p+=45;if(SALES_URL_RX.test(item.url||''))p+=55;if(/(amazon|mercado livre|shopee|aliexpress)/i.test(item.sourceName||''))p+=50;return p}
function editorialBonus(item){const text=`${item.title} ${item.snippet}`;let b=EDITORIAL_RX.test(text)?18:0;if(item.kind==='noticia')b+=10;if(item.kind==='discussao'||item.kind==='social')b+=8;if(item.kind==='video')b+=4;return b}
export const RELEVANCE_CEILING=8;
export function scoreItem(item,b,now=new Date(),queryTerm=''){const hay=normalize(`${item.title} ${item.snippet} ${item.sourceName}`),hits=[];for(const bad of b.exclude||[])if(bad&&hay.includes(normalize(bad)))return{score:0,hits:[],blocked:bad};const penalty=commercialPenalty(item);if(penalty>=55)return{score:0,hits:[],blocked:'conteúdo comercial'};let relevance=0;const q=normalize(queryTerm);if(q&&normalize(item.title).includes(q)){relevance+=4;hits.push(queryTerm)}else if(q&&hay.includes(q)){relevance+=2;hits.push(queryTerm)}for(const kw of b.keywords||[]){const k=normalize(kw);if(k&&normalize(item.title).includes(k)){relevance+=3;hits.push(kw)}else if(k&&hay.includes(k)){relevance+=1;hits.push(kw)}}if(!relevance)return{score:0,hits:[],blocked:null};const hours=item.publishedAt?Math.max(0,(now-new Date(item.publishedAt))/3600000):72,recency=hours<=24?1:hours<=72?.92:hours<=168?.78:hours<=336?.55:.3;const base=Math.min(82,(relevance/RELEVANCE_CEILING)*82),score=Math.max(0,Math.min(100,Math.round(base*recency+editorialBonus(item)-penalty)));return{score,hits:[...new Set(hits)],blocked:null}}
export function expiresAt(_item,ttlDays,now=new Date()){return new Date(now.getTime()+ttlDays*86400000).toISOString()}
export const RADAR_MAX_AGE_DAYS=14;
export function isTooOld(item,now=new Date()){if(!item.publishedAt)return false;return(now-new Date(item.publishedAt))>RADAR_MAX_AGE_DAYS*86400000}
function titleFingerprint(title){return normalize(title).replace(/\b(de|da|do|das|dos|a|o|as|os|e|em|para|por|com|um|uma|the|and|for|with)\b/g,' ').replace(/[^a-z0-9 ]/g,' ').split(/\s+/).filter(w=>w.length>3).slice(0,8)}
function similarTitle(a,b){const A=new Set(titleFingerprint(a)),B=new Set(titleFingerprint(b));if(!A.size||!B.size)return false;let same=0;for(const w of A)if(B.has(w))same++;return same/Math.min(A.size,B.size)>=.65}
export function dedupeTopics(items){const out=[];for(const item of sortItems(items)){const duplicate=out.find(x=>similarTitle(x.title,item.title));if(!duplicate)out.push(item);else duplicate.clients={...(duplicate.clients||{}),...(item.clients||{})}}return out}
export function mergeItems(existing,incoming){const byKey=new Map(existing.map(it=>[it.key,it]));let added=0;for(const item of incoming){const old=byKey.get(item.key);if(!old){byKey.set(item.key,item);added++;continue}byKey.set(item.key,{...old,clients:{...(old.clients||{}),...(item.clients||{})},expiresAt:item.expiresAt>old.expiresAt?item.expiresAt:old.expiresAt})}return{items:dedupeTopics([...byKey.values()]),added}}
export function pruneExpired(items,savedKeys=[],now=new Date()){const keep=new Set(savedKeys);return items.filter(it=>keep.has(it.key)||!it.expiresAt||new Date(it.expiresAt)>now)}
export function sortItems(items,companyId){const score=it=>companyId?(it.clients?.[companyId]?.score||0):Math.max(0,...Object.values(it.clients||{}).map(c=>c.score||0));return[...items].sort((a,b)=>score(b)-score(a)||String(b.publishedAt||'').localeCompare(String(a.publishedAt||'')))}
export function itemsForCompany(items,companyId){return companyId?items.filter(it=>it.clients?.[companyId]):items}
export function kindLabel(kind){return({noticia:'Notícia',video:'Vídeo',social:'Post',discussao:'Opinião',feed:'Feed'})[kind]||'Pauta'}
export async function runScan(briefings,{ttlDays=RADAR_TTL_DAYS_DEFAULT,settings=RADAR_DEFAULT_SETTINGS,onProgress=()=>{},signal}={}){const now=new Date(),jobs=[];for(const b of briefings)for(const query of briefingQueries(b,settings))jobs.push({briefing:b,query});const collected=new Map(),errors=[];let done=0;const parse=(text,q)=>q.parser==='youtube'?parseYouTubeHtml(text):parseFeedXml(text,q.source);for(const{briefing,query}of jobs){onProgress({done,total:jobs.length,label:`${query.source}${query.term?` · ${query.term}`:''}`});try{let body=await fetchFeed(query.url,{signal,emptyOn404:query.emptyOn404}),raws=parse(body,query);if(!raws.length&&query.retryUrl){body=await fetchFeed(query.retryUrl,{signal});raws=parse(body,query)}for(const raw of raws){if(isTooOld(raw,now))continue;raw.kind=query.kind;const{score,hits,blocked}=scoreItem(raw,briefing,now,query.term);if(blocked||score<38)continue;const key=urlKey(raw.url),entry=collected.get(key)||{key,title:raw.title,url:raw.url,snippet:cleanSnippet(raw.snippet,raw.title),sourceName:raw.sourceName,sourceType:query.source,kind:query.kind,publishedAt:raw.publishedAt,collectedAt:now.toISOString(),expiresAt:expiresAt(raw,ttlDays,now),clients:{}};entry.clients[briefing.companyId]={score,hits,term:query.term};collected.set(key,entry)}}catch(err){errors.push({source:query.source,term:query.term,message:err?.message||String(err)});if(err?.name==='AbortError')break}done++;onProgress({done,total:jobs.length,label:''})}return{items:dedupeTopics([...collected.values()]),errors,queries:jobs.length}}
