from pathlib import Path

path = Path('src/main.jsx')
text = path.read_text(encoding='utf-8')

external = '    <NotificationDeliverySettings currentUser={currentUser} statuses={statuses}/>\n'
if text.count(external) != 1:
    raise SystemExit(f'Esperava 1 bloco externo de NotificationDeliverySettings, achei {text.count(external)}')
text = text.replace(external, '', 1)

old_card = '''        <AccessConfigCard title="Notificações e alertas" open={openSection==='rule:notifications'} onToggleOpen={()=>toggleSection('rule:notifications')} accent>\n          <p className="muted" style={{marginTop:0}}>Mudanças de status só avisam sobre status que também estejam liberados em "Status disponíveis".</p>\n          <div className="checks one-col compact-checks-v3">\n            <label><input type="checkbox" checked={statusChangeNotificationsEnabled(draft.notificationStatusPrefs||{},role)} onChange={e=>setDraftValue('notificationStatusPrefs',{__all__:e.target.checked})}/>Mudança de status</label>\n            {NOTIFICATION_VISIBLE_EVENTS.map(ev=><label key={ev}><input type="checkbox" checked={(draft.notificationPrefs||[]).includes(ev)} onChange={e=>toggleEvent(ev,e.target.checked)}/>{ev}</label>)}\n          </div>\n        </AccessConfigCard>'''
new_card = '''        <AccessConfigCard title="Notificações e alertas" open={openSection==='rule:notifications'} onToggleOpen={()=>toggleSection('rule:notifications')} accent>\n          <h4 style={{marginTop:0}}>Eventos desta função</h4>\n          <p className="muted">Mudanças de status só avisam sobre status que também estejam liberados em "Status disponíveis".</p>\n          <div className="checks one-col compact-checks-v3">\n            <label><input type="checkbox" checked={statusChangeNotificationsEnabled(draft.notificationStatusPrefs||{},role)} onChange={e=>setDraftValue('notificationStatusPrefs',{__all__:e.target.checked})}/>Mudança de status</label>\n            {NOTIFICATION_VISIBLE_EVENTS.map(ev=><label key={ev}><input type="checkbox" checked={(draft.notificationPrefs||[]).includes(ev)} onChange={e=>toggleEvent(ev,e.target.checked)}/>{ev}</label>)}\n          </div>\n          <div style={{marginTop:18,paddingTop:16,borderTop:'1px solid var(--line)'}}>\n            <NotificationDeliverySettings currentUser={currentUser} statuses={statuses}/>\n          </div>\n        </AccessConfigCard>'''
if text.count(old_card) != 1:
    raise SystemExit(f'Esperava 1 card de notificações, achei {text.count(old_card)}')
text = text.replace(old_card, new_card, 1)

old_rules = '''<h3 style={{marginTop:22}}>Lembretes por status</h3>\n<p className="muted">Ative só os status que precisam cobrar alguém quando a tarefa ficar parada.</p>\n<div className="checks one-col status-notify-list compact-checks-v3" style={{gap:0}}>\n  {(statuses||[]).map(status=>{const rule=ruleFor(status.id);return <div key={status.id} style={{padding:'7px 0',borderBottom:'1px solid rgba(255,255,255,.07)'}}>\n    <label style={{margin:0,minHeight:28,display:'flex',alignItems:'center',gap:8}}>\n      <input type="checkbox" checked={rule.enabled===true} onChange={e=>updateRule(status.id,{enabled:e.target.checked})}/>\n      <span className="status-dot" style={{background:status.color}}></span>\n      <span>{status.name}</span>\n    </label>\n    {rule.enabled===true&&<div style={{margin:'8px 0 4px 24px'}}>\n      <div className="checks one-col compact-checks-v3" style={{gap:4,marginBottom:10}}>\n        <label style={{margin:0}}><input type="checkbox" checked={(rule.targets||[]).includes('client_approvers')} onChange={e=>toggleTarget(status.id,'client_approvers',e.target.checked)}/> Clientes aprovadores</label>\n        <label style={{margin:0}}><input type="checkbox" checked={(rule.targets||[]).includes('task_responsible')} onChange={e=>toggleTarget(status.id,'task_responsible',e.target.checked)}/> Responsável da tarefa</label>\n        <label style={{margin:0}}><input type="checkbox" checked={(rule.targets||[]).includes('admins')} onChange={e=>toggleTarget(status.id,'admins',e.target.checked)}/> Admins</label>\n      </div>\n      <div className="form-two">\n        <label>Primeiro lembrete após (min)<input type="number" min="0" value={rule.firstAfterMinutes} onChange={e=>updateRule(status.id,{firstAfterMinutes:e.target.value})}/></label>\n        <label>Repetir a cada (min)<input type="number" min="1" value={rule.intervalMinutes} onChange={e=>updateRule(status.id,{intervalMinutes:e.target.value})}/></label>\n      </div>\n    </div>}\n  </div>})}\n</div>'''
new_rules = '''<h3 style={{marginTop:22}}>Regras de lembrete</h3>\n<p className="muted">"Status disponíveis" controla quem pode receber. Aqui você só define a cobrança automática, os destinatários e os tempos de cada fluxo.</p>\n<div className="status-notify-list compact-checks-v3" style={{display:'flex',flexDirection:'column',gap:0}}>\n  {(statuses||[]).map(status=>{const rule=ruleFor(status.id);return <div key={status.id} style={{padding:'9px 0',borderBottom:'1px solid rgba(255,255,255,.07)'}}>\n    <div style={{display:'flex',alignItems:'center',gap:8,minHeight:32}}>\n      <span className="status-dot" style={{background:status.color}}></span>\n      <b style={{flex:1}}>{status.name}</b>\n      <label style={{margin:0,display:'flex',alignItems:'center',gap:6}}>Lembrete\n        <select value={rule.enabled===true?'on':'off'} onChange={e=>updateRule(status.id,{enabled:e.target.value==='on'})}>\n          <option value="off">Desligado</option>\n          <option value="on">Ativo</option>\n        </select>\n      </label>\n    </div>\n    {rule.enabled===true&&<div style={{margin:'10px 0 4px 24px'}}>\n      <div className="checks one-col compact-checks-v3" style={{gap:4,marginBottom:10}}>\n        <label style={{margin:0}}><input type="checkbox" checked={(rule.targets||[]).includes('client_approvers')} onChange={e=>toggleTarget(status.id,'client_approvers',e.target.checked)}/> Clientes aprovadores</label>\n        <label style={{margin:0}}><input type="checkbox" checked={(rule.targets||[]).includes('task_responsible')} onChange={e=>toggleTarget(status.id,'task_responsible',e.target.checked)}/> Responsável da tarefa</label>\n        <label style={{margin:0}}><input type="checkbox" checked={(rule.targets||[]).includes('admins')} onChange={e=>toggleTarget(status.id,'admins',e.target.checked)}/> Admins</label>\n      </div>\n      <div className="form-two">\n        <label>Primeiro lembrete após (min)<input type="number" min="0" value={rule.firstAfterMinutes} onChange={e=>updateRule(status.id,{firstAfterMinutes:e.target.value})}/></label>\n        <label>Repetir a cada (min)<input type="number" min="1" value={rule.intervalMinutes} onChange={e=>updateRule(status.id,{intervalMinutes:e.target.value})}/></label>\n      </div>\n    </div>}\n  </div>})}\n</div>'''
if text.count(old_rules) != 1:
    raise SystemExit(f'Esperava 1 bloco de lembretes por status, achei {text.count(old_rules)}')
text = text.replace(old_rules, new_rules, 1)

path.write_text(text, encoding='utf-8')
print('Etapa 5 aplicada de forma cirúrgica em src/main.jsx')
