from pathlib import Path
import re


def replace_once(text, old, new, label):
    if old not in text:
        raise SystemExit(f'Bloco não encontrado: {label}')
    return text.replace(old, new, 1)

# 1) Catálogo de permissões: painel de notificações fica só com ações/visibilidade do painel.
panel_path = Path('src/services/panelAccess.js')
panel = panel_path.read_text(encoding='utf-8')
old = """export const NOTIFICATION_PANEL_PERMISSION_ITEMS = Object.freeze([\n  Object.freeze({id:'showTabs',label:'Pendentes e concluídas'}),\n  Object.freeze({id:'canEnableAlerts',label:'Ativar som e notificações'}),\n  Object.freeze({id:'canOpenTasks',label:'Abrir tarefas'}),\n  Object.freeze({id:'canComplete',label:'Concluir notificações'}),\n  Object.freeze({id:'canCompleteAll',label:'Concluir todas as pendentes'}),\n  Object.freeze({id:'canDeleteCompleted',label:'Limpar notificações concluídas'}),\n  Object.freeze({id:'showDateTime',label:'Data e hora'}),\n  Object.freeze({id:'showCompany',label:'Empresa'}),\n  Object.freeze({id:'showResponsible',label:'Responsável'}),\n  Object.freeze({id:'showPostDate',label:'Data do post'}),\n  Object.freeze({id:'showDeadline',label:'Prazo'}),\n  Object.freeze({id:'showStatus',label:'Status'}),\n]);"""
new = """export const NOTIFICATION_PANEL_PERMISSION_ITEMS = Object.freeze([\n  Object.freeze({id:'showTabs',label:'Pendentes e concluídas'}),\n  Object.freeze({id:'canComplete',label:'Concluir notificações'}),\n  Object.freeze({id:'canCompleteAll',label:'Concluir todas as pendentes'}),\n  Object.freeze({id:'canDeleteCompleted',label:'Limpar notificações concluídas'}),\n]);"""
panel = replace_once(panel, old, new, 'catálogo do painel de notificações')
panel = replace_once(panel, "    notificationStatusPrefs:{},\n", "    notificationStatusPrefs:{__all__:normalizedRole!=='client'},\n", 'padrão global de mudança de status')
panel_path.write_text(panel, encoding='utf-8')

# 2) Frontend: status disponíveis vira trava-mãe; notificações/alertas saem do painel.
main_path = Path('src/main.jsx')
main = main_path.read_text(encoding='utf-8')
old = """function wantsNotification(user, event, statusId){\n  if(!user?.active || user.role==='client') return false;\n  const statusPrefs=user.notificationStatusPrefs||{};\n  if(event==='Status da tarefa'){\n    return !!statusId && (statusPrefs[statusId]??true);\n  }\n  if(BLOCKED_NOTIFICATION_EVENTS.has(event)) return false;\n  if(!NOTIFICATION_VISIBLE_EVENTS.includes(event)) return false;\n  const prefs=Array.isArray(user.notificationPrefs)?user.notificationPrefs:defaultNotificationPrefsForRole(user.role);\n  return prefs.includes(event);\n}"""
new = """function wantsNotification(user, event, statusId){\n  if(!user?.active) return false;\n  const statusPrefs=user.notificationStatusPrefs||{};\n  if(event==='Status da tarefa'){\n    if(!statusId) return false;\n    const visibleStatuses=Array.isArray(user.visibleStatuses)?user.visibleStatuses:[];\n    if(user.role!=='admin' && visibleStatuses.length && !visibleStatuses.includes(statusId)) return false;\n    return statusPrefs.__all__ ?? (user.role!=='client');\n  }\n  if(BLOCKED_NOTIFICATION_EVENTS.has(event)) return false;\n  if(!NOTIFICATION_VISIBLE_EVENTS.includes(event)) return false;\n  const prefs=Array.isArray(user.notificationPrefs)?user.notificationPrefs:defaultNotificationPrefsForRole(user.role);\n  return prefs.includes(event);\n}"""
main = replace_once(main, old, new, 'wantsNotification')

old = """  const notificationsDiff=!deepPermEqual(notificationPanelConfig, roleDefault.notificationPanel||builtInNotificationPanelPermissionsForRole(f.role))\n    || !deepPermEqual(f.notificationPrefs||[], roleDefault.notificationPrefs||[])\n    || !deepPermEqual(f.notificationStatusPrefs||{}, roleDefault.notificationStatusPrefs||{});"""
new = """  const notificationPanelDiff=!deepPermEqual(notificationPanelConfig, roleDefault.notificationPanel||builtInNotificationPanelPermissionsForRole(f.role));\n  const notificationRulesDiff=!deepPermEqual(f.notificationPrefs||[], roleDefault.notificationPrefs||[])\n    || (f.notificationStatusPrefs?.__all__??(f.role!=='client'))!==(roleDefault.notificationStatusPrefs?.__all__??(f.role!=='client'));\n  const notificationsDiff=notificationPanelDiff||notificationRulesDiff;"""
main = replace_once(main, old, new, 'diferenças de notificações')

pattern = re.compile(r"    if\(panel\.id==='notifications'\) return <div>.*?    if\(panel\.id==='dashboard'\) return <div>", re.S)
replacement = """    if(panel.id==='notifications') return <div>\n      <div style={notificationInheritance!=='custom'?{pointerEvents:'none'}:undefined}>\n        <h3 style={{display:'flex',alignItems:'center',gap:7}}>{notificationPanelDiff&&<span className=\"item-custom-dot\"/>}<span style={{opacity:notificationPanelDiff?1:.62}}>Painel e ações</span></h3>\n        <div className=\"checks one-col compact-checks-v3\">{NOTIFICATION_PANEL_PERMISSION_ITEMS.map(item=>{const def=(roleDefault.notificationPanel||builtInNotificationPanelPermissionsForRole(f.role))?.[item.id];const itemDiff=notificationPanelConfig?.[item.id]!==def;return <label key={item.id} className={itemDiff?'custom-access-field':undefined} style={!itemDiff?{opacity:.62}:undefined}>{itemDiff&&<span className=\"item-custom-dot\"/>}<input type=\"checkbox\" checked={notificationPanelConfig?.[item.id]===true} onChange={e=>toggleNotificationPanelPermission(item.id,e.target.checked)}/>{item.label}</label>;})}</div>\n        <small className=\"muted\" style={{display:'block',marginTop:10}}>O conteúdo exibido na notificação herda as permissões da tarefa. Informações que este usuário não pode ver na tarefa também não devem aparecer aqui.</small>\n      </div>\n    </div>;\n    if(panel.id==='dashboard') return <div>"""
main, count = pattern.subn(replacement, main, count=1)
if count != 1:
    raise SystemExit('Bloco individual do painel de notificações não encontrado')

anchor = """      {f.role!=='admin'&&<AccessConfigCard title=\"Tipos de tarefas disponíveis\" open={openSection==='rule:types'} onToggleOpen={()=>toggleSection('rule:types')} accent customized={typesDiff}>\n        <div style={typeInheritance!=='custom'?{pointerEvents:'none'}:undefined}>\n          <TaskTypeVisibilityChecks selected={typeInheritance==='custom'?(f.visibleTypes||[]):(roleDefault.visibleTypes||TASK_TYPES)} onToggle={toggleType} defaultSelected={roleDefault.visibleTypes||TASK_TYPES}/>\n        </div>\n      </AccessConfigCard>}\n\n"""
insert = anchor + """      <AccessConfigCard title=\"Notificações e alertas\" open={openSection==='rule:notifications'} onToggleOpen={()=>toggleSection('rule:notifications')} accent customized={notificationRulesDiff}>\n        <div style={notificationInheritance!=='custom'?{pointerEvents:'none'}:undefined}>\n          <p className=\"muted\" style={{marginTop:0}}>Define quais eventos podem avisar este usuário. Mudanças de status só geram aviso quando o status também está liberado em \"Status disponíveis\". O push acompanha essas mesmas regras.</p>\n          <div className=\"checks one-col compact-checks-v3\">\n            {(()=>{const checked=notificationInheritance==='custom'?(f.notificationStatusPrefs?.__all__??(f.role!=='client')):(roleDefault.notificationStatusPrefs?.__all__??(f.role!=='client'));const def=roleDefault.notificationStatusPrefs?.__all__??(f.role!=='client');const diff=checked!==def;return <label className={diff?'custom-access-field':undefined} style={!diff?{opacity:.62}:undefined}>{diff&&<span className=\"item-custom-dot\"/>}<input type=\"checkbox\" checked={checked} onChange={e=>set('notificationStatusPrefs',{...(f.notificationStatusPrefs||{}),__all__:e.target.checked})}/>Mudança de status</label>;})()}\n            {events.map(ev=>{const checked=(notificationInheritance==='custom'?(f.notificationPrefs||[]):(roleDefault.notificationPrefs||[])).includes(ev);const def=(roleDefault.notificationPrefs||[]).includes(ev);const diff=checked!==def;return <label key={ev} className={diff?'custom-access-field':undefined} style={!diff?{opacity:.62}:undefined}>{diff&&<span className=\"item-custom-dot\"/>}<input type=\"checkbox\" checked={checked} onChange={e=>toggleEvent(ev,e.target.checked)}/>{ev}</label>;})}\n          </div>\n        </div>\n      </AccessConfigCard>\n\n"""
main = replace_once(main, anchor, insert, 'seção individual Notificações e alertas')
main = main.replace('          notifications:notificationsDiff,', '          notifications:notificationPanelDiff,', 1)

pattern = re.compile(r"    if\(panel\.id==='notifications'\) return <div>.*?    if\(panel\.id==='dashboard'\) return <div><h4>", re.S)
replacement = """    if(panel.id==='notifications') return <div>\n      <h4>Painel e ações</h4><div className=\"checks one-col compact-checks-v3\">{NOTIFICATION_PANEL_PERMISSION_ITEMS.map(item=><label key={item.id}><input type=\"checkbox\" checked={draft.notificationPanel?.[item.id]===true} onChange={e=>toggleNotificationPanelPermission(item.id,e.target.checked)}/>{item.label}</label>)}</div>\n      <small className=\"muted\" style={{display:'block',marginTop:10}}>Os dados mostrados neste painel devem acompanhar as permissões já definidas em \"Tarefa aberta\".</small>\n    </div>;\n    if(panel.id==='dashboard') return <div><h4>"""
main, count = pattern.subn(replacement, main, count=1)
if count != 1:
    raise SystemExit('Bloco padrão do painel de notificações não encontrado')

anchor = """        {role!=='admin'&&<AccessConfigCard title=\"Tipos de tarefas disponíveis\" open={openSection==='rule:types'} onToggleOpen={()=>toggleSection('rule:types')} accent>\n          <TaskTypeVisibilityChecks selected={draft.visibleTypes||TASK_TYPES} onToggle={toggleType}/>\n        </AccessConfigCard>}\n\n"""
insert = anchor + """        <AccessConfigCard title=\"Notificações e alertas\" open={openSection==='rule:notifications'} onToggleOpen={()=>toggleSection('rule:notifications')} accent>\n          <p className=\"muted\" style={{marginTop:0}}>Os alertas respeitam automaticamente os status liberados acima. Push e notificação interna usam a mesma regra de evento; lembretes continuam configurados separadamente por tempo e destinatário.</p>\n          <div className=\"checks one-col compact-checks-v3\">\n            <label><input type=\"checkbox\" checked={draft.notificationStatusPrefs?.__all__??(role!=='client')} onChange={e=>setDraftValue('notificationStatusPrefs',{...(draft.notificationStatusPrefs||{}),__all__:e.target.checked})}/>Mudança de status</label>\n            {NOTIFICATION_VISIBLE_EVENTS.map(ev=><label key={ev}><input type=\"checkbox\" checked={(draft.notificationPrefs||[]).includes(ev)} onChange={e=>toggleEvent(ev,e.target.checked)}/>{ev}</label>)}\n          </div>\n        </AccessConfigCard>\n\n"""
main = replace_once(main, anchor, insert, 'seção padrão Notificações e alertas')
main_path.write_text(main, encoding='utf-8')

# 3) Push: nenhuma entrega relacionada a status pode furar Status disponíveis.
push_path = Path('supabase/functions/process-notification-push-queue/index.ts')
push = push_path.read_text(encoding='utf-8')
push = replace_once(push, '.select("id,role,active,last_seen_at")', '.select("id,role,active,last_seen_at,visible_statuses")', 'perfil com status visíveis')
old = """  return [...ids];\n}\n\nasync function generateReminderQueue()"""
new = """  if (!ids.size) return [];\n  const { data: profiles } = await supabase\n    .from(\"profiles\")\n    .select(\"id,role,active,visible_statuses\")\n    .eq(\"organization_id\", organizationId)\n    .in(\"id\", [...ids]);\n  return (profiles ?? [])\n    .filter((profile: any) => {\n      if (profile.active === false) return false;\n      if (profile.role === \"admin\") return true;\n      const visible = Array.isArray(profile.visible_statuses) ? profile.visible_statuses : [];\n      return !task?.status || visible.length === 0 || visible.includes(task.status);\n    })\n    .map((profile: any) => String(profile.id));\n}\n\nasync function generateReminderQueue()"""
push = replace_once(push, old, new, 'filtro de destinatários de lembrete')
old = """  const settings = await deliverySettings(row.organization_id);\n  if (!settings.enabled) {\n    await markRows(ids, { status: \"skipped\", skip_reason: \"delivery_disabled\" });\n    return { sent: 0, skipped: 1 };\n  }\n\n  const lastSeenMs"""
new = """  const settings = await deliverySettings(row.organization_id);\n  if (!settings.enabled) {\n    await markRows(ids, { status: \"skipped\", skip_reason: \"delivery_disabled\" });\n    return { sent: 0, skipped: 1 };\n  }\n\n  if (row.status_id && profile.role !== \"admin\") {\n    const visible = Array.isArray(profile.visible_statuses) ? profile.visible_statuses : [];\n    if (visible.length && !visible.includes(row.status_id)) {\n      await markRows(ids, { status: \"skipped\", skip_reason: \"status_not_visible\" });\n      return { sent: 0, skipped: 1 };\n    }\n  }\n\n  const lastSeenMs"""
push = replace_once(push, old, new, 'trava final de push por status')
push_path.write_text(push, encoding='utf-8')

print('Refatoração aplicada aos arquivos Beta.')
